### ISSUE TITLE
Get ship angle

### ISSUE THREAD

**Issue by ModellbahnFreak** [nk-coding/SpaceGame#1]
Feature request: Ability to get the angle of the comute core to the movement direction ("relative angle") and the angle of the comupute core to the absolute coordinate system ("absolute angle") alternatively to the relative angle the angle of the movement direction to the coordinate system

**Comment by nk-coding** [comment]
sort of implemented with f643759ef9d057bad5f6c31c8dbc854ec9e012c5 and 3608d5882112fef1e02ef452876877558d7aa2c0
Rotation (ComputeCore) provides the angle of the Ship in radians
ShipPosition (ComputeCore) provides the position of the Ship in the universe (with an x and y coordinate)
Position (every Component) provides the center position of the Component in the universe (with x and y)
Velocity (ComputeCore) now consists of dx and dy, the angle can be calculated via atan2
